wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced_subsample
max_depth:
  value: 13
min_samples_leaf:
  value: 2
min_samples_split:
  value: 2
n_estimators:
  value: 41
warm_start:
  value: true
