wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced
max_depth:
  value: 15
min_samples_leaf:
  value: 4
min_samples_split:
  value: 7
n_estimators:
  value: 56
warm_start:
  value: false
