wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 3
min_samples_leaf:
  value: 2
min_samples_split:
  value: 3
n_estimators:
  value: 62
warm_start:
  value: false
