wandb_version: 1

bootstrap:
  desc: null
  value: false
class_weight:
  desc: null
  value: balanced
max_depth:
  desc: null
  value: 3
min_samples_leaf:
  desc: null
  value: 2
min_samples_split:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 62
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688554933.692593
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
      9:
        1: mlops_zoomcamp
