wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 6
min_samples_leaf:
  value: 3
min_samples_split:
  value: 10
n_estimators:
  value: 91
warm_start:
  value: false
