wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced
max_depth:
  value: 12
min_samples_leaf:
  value: 3
min_samples_split:
  value: 6
n_estimators:
  value: 59
warm_start:
  value: false
