wandb_version: 1

bootstrap:
  desc: null
  value: true
class_weight:
  desc: null
  value: balanced
max_depth:
  desc: null
  value: 13
min_samples_leaf:
  desc: null
  value: 4
min_samples_split:
  desc: null
  value: 10
n_estimators:
  desc: null
  value: 55
warm_start:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688554873.870376
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
      9:
        1: mlops_zoomcamp
