wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688149377.76856
    t:
      1:
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 1
      - 5
    framework: sklearn
